services:
  localstack:
    image: localstack/localstack:3.0
    container_name: smile_infra
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=us-east-1
      - ACTIVATE_PRO=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smile_api
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=http://localstack:4566
      - DYNAMODB_TABLE=SmileTable
    depends_on:
      - localstack
